import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import {
  ArrowLeft,
  ArrowRight,
  BookOpen,
  Briefcase,
  Calendar,
  CheckSquare,
  Clock,
  FileText,
  ListChecks,
  RefreshCw,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import {
  getAllPosts,
  getPostBySlug,
  type BlogInlineLink,
  type BlogPost,
} from "@/lib/posts";
import CTABanner from "@/components/home/CTABanner";
import InlineCTA from "@/components/blog/InlineCTA";
import StickyCTA from "@/components/blog/StickyCTA";
import TableOfContents, {
  headingSlug,
} from "@/components/blog/TableOfContents";
import FaqSection from "@/components/blog/FaqSection";
import JsonLd from "@/components/seo/JsonLd";
import WhatsAppIcon from "@/components/ui/WhatsAppIcon";
import { whatsappLink } from "@/lib/contact";
import { SITE } from "@/lib/seo";

interface Props {
  params: Promise<{ slug: string }>;
}

export async function generateStaticParams() {
  return getAllPosts().map((post) => ({ slug: post.slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const post = getPostBySlug(slug);
  if (!post) return {};

  const url = `${SITE.url}/blog/${post.slug}`;
  // Per-article OG image generated by app/blog/[slug]/opengraph-image.tsx
  const articleOg = `${SITE.url}/blog/${post.slug}/opengraph-image`;

  return {
    title: post.title,
    description: post.description,
    keywords: post.keywords ? [...post.keywords] : undefined,
    alternates: { canonical: url },
    openGraph: {
      type: "article",
      title: post.title,
      description: post.description,
      url,
      siteName: SITE.name,
      locale: "en_AE",
      publishedTime: post.date,
      modifiedTime: post.dateModified ?? post.date,
      authors: [SITE.name],
      tags: post.keywords ? [...post.keywords] : [post.category],
      images: [
        {
          url: articleOg,
          width: 1200,
          height: 630,
          alt: post.title,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: post.title,
      description: post.description,
      images: [articleOg],
    },
  };
}

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

/** Pick the best CTA preset for a given article based on its category. */
function ctaMessageForCategory(
  category: string
): "default" | "getEjari" | "renewal" {
  const lower = category.toLowerCase();
  if (lower.includes("renewal") || lower.includes("how-to")) return "renewal";
  if (lower.includes("trade")) return "renewal";
  return "getEjari";
}

/**
 * Category → hero icon + accent gradient. Gives every article its own visual
 * identity in the hero. The accent classes also flow into the icon tile so
 * cards in feeds + on the index look distinct.
 */
function heroIconForCategory(category: string): {
  Icon: LucideIcon;
  tone: string;
} {
  const c = category.toLowerCase();
  if (c.includes("compliance"))
    return { Icon: CheckSquare, tone: "from-primary to-primary-dark" };
  if (c.includes("strategy"))
    return { Icon: Briefcase, tone: "from-foreground to-primary" };
  if (c.includes("how"))
    return { Icon: ListChecks, tone: "from-coral to-amber" };
  if (c.includes("trade"))
    return { Icon: RefreshCw, tone: "from-primary-dark to-foreground" };
  if (c.includes("basic"))
    return { Icon: BookOpen, tone: "from-primary to-amber" };
  return { Icon: FileText, tone: "from-primary to-primary-dark" };
}

/**
 * Render a paragraph string with optional inline cross-links. Each link's
 * `match` substring (first occurrence, case-sensitive) is wrapped in a
 * Next `<Link>`. Pure text paragraphs return the original string.
 */
function renderParagraph(
  text: string,
  links?: BlogInlineLink[]
): React.ReactNode {
  if (!links || links.length === 0) return text;

  const escaped = links.map((l) =>
    l.match.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
  );
  const re = new RegExp(`(${escaped.join("|")})`);
  const parts = text.split(re);

  return parts.map((part, i) => {
    const link = links.find((l) => l.match === part);
    if (link) {
      return (
        <Link
          key={i}
          href={link.href}
          className="font-medium text-primary underline decoration-primary/30 underline-offset-4 transition-colors hover:text-primary-dark hover:decoration-primary"
        >
          {part}
        </Link>
      );
    }
    return <span key={i}>{part}</span>;
  });
}

function buildArticleLd(
  post: BlogPost,
  url: string,
  articleOg: string
): Record<string, unknown> {
  return {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    "@id": `${url}#article`,
    headline: post.title,
    description: post.description,
    datePublished: post.date,
    dateModified: post.dateModified ?? post.date,
    inLanguage: "en-AE",
    articleSection: post.category,
    keywords: post.keywords?.join(", "),
    wordCount: post.content
      .map((b) => {
        if (b.type === "p" || b.type === "h2" || b.type === "h3") {
          return b.text?.split(/\s+/).length ?? 0;
        }
        if (b.type === "ul" || b.type === "ol") {
          return b.items.reduce(
            (sum, item) => sum + item.split(/\s+/).length,
            0
          );
        }
        return 0;
      })
      .reduce((a, b) => a + b, 0),
    // Organization-as-author. Articles are written by the MyEjari team and
    // published as the brand's voice — no individual byline by design.
    author: { "@id": `${SITE.url}/#organization` },
    publisher: { "@id": `${SITE.url}/#organization` },
    mainEntityOfPage: { "@type": "WebPage", "@id": url },
    image: [articleOg],
    url,
    isPartOf: { "@id": `${SITE.url}/blog#blog` },
    about: post.keywords?.map((k) => ({ "@type": "Thing", name: k })),
  };
}

export default async function BlogPostPage({ params }: Props) {
  const { slug } = await params;
  const post = getPostBySlug(slug);
  if (!post) notFound();

  const allPosts = getAllPosts();
  const relatedPosts = allPosts
    .filter((p) => p.slug !== post.slug)
    .slice(0, 3);

  const url = `${SITE.url}/blog/${post.slug}`;
  const articleOg = `${SITE.url}/blog/${post.slug}/opengraph-image`;
  const stickyMessage = ctaMessageForCategory(post.category);
  const { Icon: HeroIcon, tone: heroTone } = heroIconForCategory(post.category);

  // Build TOC entries from H2 blocks.
  const tocItems = post.content
    .filter((b) => b.type === "h2")
    .map((b) => ({
      id: headingSlug((b as { type: "h2"; text: string }).text),
      text: (b as { type: "h2"; text: string }).text,
    }));

  // ── JSON-LD (BlogPosting + FAQ + Breadcrumb) ─────────────────────
  const articleLd = buildArticleLd(post, url, articleOg);

  const faqLd = post.faqs?.length
    ? {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        inLanguage: "en-AE",
        mainEntity: post.faqs.map((f) => ({
          "@type": "Question",
          name: f.q,
          acceptedAnswer: { "@type": "Answer", text: f.a },
        })),
      }
    : null;

  const breadcrumbLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: SITE.url },
      {
        "@type": "ListItem",
        position: 2,
        name: "Blog",
        item: `${SITE.url}/blog`,
      },
      { "@type": "ListItem", position: 3, name: post.title, item: url },
    ],
  };

  const ldData: Record<string, unknown>[] = [articleLd, breadcrumbLd];
  if (faqLd) ldData.push(faqLd);

  return (
    <>
      <article>
        {/* ── Hero ───────────────────────────────────────────── */}
        <header className="relative overflow-hidden bg-gradient-to-b from-primary-light to-white px-6 pt-12 pb-16">
          <div className="absolute inset-0 bg-grid" />
          <div className="absolute -top-32 -left-32 h-96 w-96 rounded-full bg-primary/5 blur-3xl" />
          <div className="absolute -bottom-24 -right-24 h-80 w-80 rounded-full bg-amber/15 blur-3xl" />

          <div className="relative z-10 mx-auto max-w-3xl">
            <Link
              href="/blog"
              className="inline-flex items-center gap-1.5 text-sm font-medium text-primary transition-colors hover:text-primary-dark"
            >
              <ArrowLeft size={16} /> Back to all guides
            </Link>

            <div className="mt-6 flex items-center gap-3">
              <span
                aria-hidden="true"
                className={`flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br ${heroTone} text-white shadow-soft`}
              >
                <HeroIcon size={22} strokeWidth={2.2} />
              </span>
              <span className="inline-block rounded-full bg-primary-light px-3 py-1 text-xs font-semibold uppercase tracking-wider text-primary">
                {post.category}
              </span>
            </div>

            <h1 className="mt-5 text-3xl font-bold leading-tight tracking-tight text-foreground sm:text-4xl lg:text-5xl">
              {post.title}
            </h1>

            <p className="mt-5 text-lg text-gray leading-relaxed">
              {post.description}
            </p>

            <div className="mt-6 flex flex-wrap items-center gap-x-5 gap-y-2 text-sm text-gray">
              <span className="inline-flex items-center gap-1.5">
                <Calendar size={14} />
                <time dateTime={post.dateModified ?? post.date}>
                  {formatDate(post.dateModified ?? post.date)}
                </time>
              </span>
              <span className="inline-flex items-center gap-1.5">
                <Clock size={14} /> {post.readingTime}
              </span>
            </div>

            {/* Hero CTA — top of article, highest intent */}
            <div className="mt-8">
              <a
                href={whatsappLink(stickyMessage)}
                target="_blank"
                rel="noopener noreferrer"
                data-track="whatsapp"
                data-source="blog_hero_cta"
                className="group inline-flex items-center gap-2.5 rounded-full bg-foreground px-6 py-3.5 text-sm font-semibold text-white shadow-soft transition-all hover:-translate-y-0.5 hover:bg-primary"
              >
                <WhatsAppIcon size={16} />
                Chat with us
                <ArrowRight
                  size={14}
                  className="transition-transform group-hover:translate-x-0.5"
                />
              </a>
            </div>
          </div>
        </header>

        {/* ── Body — 2-col on desktop with sticky sidebar CTA ──── */}
        <div className="mx-auto max-w-6xl px-6 py-14">
          <div className="grid grid-cols-1 gap-12 lg:grid-cols-[minmax(0,1fr)_320px]">
            <div>
              <TableOfContents items={tocItems} />

              <div className="space-y-6 text-foreground/85 leading-relaxed">
                {post.content.map((block, i) => {
                  if (block.type === "h2") {
                    return (
                      <h2
                        key={i}
                        id={headingSlug(block.text)}
                        className="scroll-mt-24 pt-6 text-2xl font-semibold tracking-tight text-foreground sm:text-3xl"
                      >
                        {block.text}
                      </h2>
                    );
                  }
                  if (block.type === "h3") {
                    return (
                      <h3
                        key={i}
                        className="pt-2 text-xl font-semibold text-foreground"
                      >
                        {block.text}
                      </h3>
                    );
                  }
                  if (block.type === "ul") {
                    return (
                      <ul key={i} className="ml-6 list-disc space-y-2.5">
                        {block.items.map((item, j) => (
                          <li
                            key={j}
                            className="text-base sm:text-lg leading-relaxed"
                          >
                            {item}
                          </li>
                        ))}
                      </ul>
                    );
                  }
                  if (block.type === "ol") {
                    return (
                      <ol key={i} className="ml-6 list-decimal space-y-2.5">
                        {block.items.map((item, j) => (
                          <li
                            key={j}
                            className="text-base sm:text-lg leading-relaxed pl-1"
                          >
                            {item}
                          </li>
                        ))}
                      </ol>
                    );
                  }
                  if (block.type === "quote") {
                    return (
                      <blockquote
                        key={i}
                        className="border-l-4 border-primary bg-primary-light/50 px-5 py-3 italic text-foreground/75"
                      >
                        {block.text}
                      </blockquote>
                    );
                  }
                  if (block.type === "cta") {
                    return (
                      <InlineCTA
                        key={i}
                        heading={block.heading}
                        sub={block.sub}
                        label={block.label}
                        message={block.message}
                        source={block.source}
                      />
                    );
                  }
                  return (
                    <p key={i} className="text-base sm:text-lg">
                      {renderParagraph(block.text, block.links)}
                    </p>
                  );
                })}
              </div>

              {post.faqs && post.faqs.length > 0 && (
                <FaqSection faqs={post.faqs} />
              )}

              {/* Related posts — internal linking for SEO + UX */}
              {relatedPosts.length > 0 && (
                <aside className="mt-16 border-t border-border pt-10">
                  <h2 className="text-sm font-semibold uppercase tracking-wider text-gray">
                    Related guides
                  </h2>
                  <div className="mt-5 grid gap-4 sm:grid-cols-2">
                    {relatedPosts.map((rp) => (
                      <Link
                        key={rp.slug}
                        href={`/blog/${rp.slug}`}
                        className="group flex flex-col rounded-2xl border border-border bg-white p-6 transition-all hover:-translate-y-1 hover:shadow-soft"
                      >
                        <span className="inline-block w-fit rounded-full bg-primary-light px-2.5 py-0.5 text-[11px] font-semibold uppercase tracking-wider text-primary">
                          {rp.category}
                        </span>
                        <h3 className="mt-3 text-base font-semibold text-foreground group-hover:text-primary">
                          {rp.title}
                        </h3>
                        <span className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-primary transition-transform group-hover:translate-x-1">
                          Read article <ArrowRight size={12} />
                        </span>
                      </Link>
                    ))}
                  </div>
                </aside>
              )}
            </div>

            {/* Sticky desktop sidebar CTA — visible throughout the read */}
            <div>
              <StickyCTA
                message={stickyMessage}
                source={`blog_sticky_${post.slug}`}
              />
            </div>
          </div>
        </div>
      </article>

      <CTABanner />

      <JsonLd data={ldData} />
    </>
  );
}
